/* Whack-a-Track mini-game for the Rizney YouTube player. */
(() => {
  "use strict";
  const TRACK_HEALTH=24,GAME_DURATION=80,MOLE_VISIBLE_MS=460,MOLE_INTERVAL_MS=1400;
  const youtube=()=>window.rizneyPlayer||window.player||null,$=(s,r=document)=>r.querySelector(s),controls=()=>$(".controls");
  let game,active=false,trackHealth=TRACK_HEALTH,secondsLeft=GAME_DURATION,moleTimer,hideTimer,gameTimer;
  const setToolbarHidden=hidden=>controls()?.classList.toggle("toolbar-hidden",hidden);
  function setupToolbar(){const style=document.createElement("style");style.textContent=`.controls{position:sticky;top:var(--player-dock-height,0px);z-index:90;transition:opacity .18s ease,visibility .18s ease}.controls.toolbar-hidden{visibility:hidden;opacity:0;pointer-events:none}#reading,#whack-a-track-game{scroll-margin-top:calc(var(--player-dock-height,0px) + 8px)}`;document.head.appendChild(style);const dock=$(".player-dock");if(dock){const update=()=>document.documentElement.style.setProperty("--player-dock-height",`${dock.offsetHeight}px`);update();window.addEventListener("resize",update,{passive:true});}const cards=$("#draw-cards"),whack=$("#whack-track");if(cards&&whack)whack.parentElement.insertBefore(cards,whack);setToolbarHidden(false);}
  const playing=()=>{const p=youtube();return p&&typeof p.getPlayerState==="function"&&window.YT&&p.getPlayerState()===YT.PlayerState.PLAYING;};
  function createGame(){if(game)return game;const panel=document.createElement("section");panel.id="whack-a-track-game";panel.innerHTML=`<h2>Whack-a-Track</h2><p id="wat-status" aria-live="polite"></p><p><span id="wat-time">${GAME_DURATION}</span>s</p><progress id="wat-health" max="${TRACK_HEALTH}" value="${TRACK_HEALTH}"></progress><div id="wat-board"></div><button id="wat-close" type="button">Close game</button>`;Object.assign(panel.style,{maxWidth:"min(92vw,620px)",margin:"8px auto 18px",padding:"10px 14px 14px",textAlign:"center",background:"#120b18",border:"2px solid #d4af37",borderRadius:"12px"});const board=$("#wat-board",panel);Object.assign(board.style,{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:"10px",margin:"18px auto"});for(let i=0;i<6;i++){const hole=document.createElement("button");hole.type="button";hole.className="wat-hole";hole.textContent="🕳️";hole.dataset.active="false";Object.assign(hole.style,{minHeight:"76px",fontSize:"2rem"});hole.onclick=()=>{if(!active||hole.dataset.active!=="true")return;hole.dataset.active="false";hole.textContent="💥";$("#wat-health",panel).value=--trackHealth;if(trackHealth<=0)finish(true);};board.append(hole);}$("#wat-close",panel).onclick=closeGame;($(".player-dock")||$("main")||document.body).insertAdjacentElement("afterend",panel);panel.hidden=true;new MutationObserver(()=>setToolbarHidden(!panel.hidden)).observe(panel,{attributes:true,attributeFilter:["hidden"]});return game={panel,board,status:$("#wat-status",panel)};}
  function hide(){game.board.querySelectorAll(".wat-hole").forEach(h=>{h.dataset.active="false";h.textContent="🕳️";});}
  function spawn(){if(!active)return;const holes=[...game.board.children],hole=holes[Math.floor(Math.random()*holes.length)];hide();hole.dataset.active="true";hole.textContent="🐭";clearTimeout(hideTimer);hideTimer=setTimeout(()=>{hole.dataset.active="false";hole.textContent="🕳️";},MOLE_VISIBLE_MS);moleTimer=setTimeout(spawn,MOLE_INTERVAL_MS);}
  function finish(won){active=false;clearTimeout(moleTimer);clearTimeout(hideTimer);clearInterval(gameTimer);hide();game.status.textContent=won?"💥 TRACK WHACKED!":"The track survived. Try again!";}
  function closeGame(){active=false;clearTimeout(moleTimer);clearTimeout(hideTimer);clearInterval(gameTimer);if(game)game.panel.hidden=true;}
  function start(event){event?.preventDefault();game=createGame();game.panel.hidden=false;trackHealth=TRACK_HEALTH;$("#wat-health",game.panel).value=trackHealth;if(!playing()){game.status.textContent="Play a track to start the game.";return;}active=true;secondsLeft=GAME_DURATION;$("#wat-time",game.panel).textContent=secondsLeft;game.status.textContent="Whack every mouse before the clock runs out!";clearInterval(gameTimer);gameTimer=setInterval(()=>{if(--secondsLeft<=0)finish(false);$("#wat-time",game.panel).textContent=secondsLeft;},1000);spawn();}
  function init(){setupToolbar();const button=$("#whack-track");if(button&&!button.dataset.whackGameBound){button.dataset.whackGameBound="true";button.onclick=start;}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
